# Generated by Django 5.0.6 on 2024-06-27 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deseados',
            name='usuario',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='usuario',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='cliente',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='historial_c',
            name='usuario',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
