# Generated by Django 5.0.6 on 2024-07-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_deseados_producto_deseados_productos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='desc',
            field=models.CharField(default='Sin descripcion', max_length=500),
        ),
    ]
