# Generated by Django 5.0.6 on 2024-06-28 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_carrito_cantidad_remove_carrito_valor_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemCarrito',
            new_name='ElementoCarrito',
        ),
    ]
