# Generated by Django 5.0.6 on 2024-06-28 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_itemcarrito_elementocarrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementocarrito',
            name='carrito',
        ),
        migrations.RemoveField(
            model_name='elementocarrito',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='ElementoCarrito',
        ),
    ]
